apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    type: mysql 
    name: jegan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
