apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    type: wordpress
    name: jegan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
