- name: This Ansible Playbook will create an OpenShift Project
  hosts: localhost
  tasks:
  - name: Create a project
    k8s:
      name: tektutor
      api_version: v1
      kind: Namespace
      state: present
