- name: This Ansible Playbook will deploy nginx application into OpenShift Cluster
  hosts: localhost
  tasks:

  - name: Create a k8s namespace
    k8s:
      name: tektutor
      api_version: v1
      kind: Namespace
      state: present

  - name: Create a BuildConfig 
    k8s:
      state: present
      src: ../../Day5/build-config/build-config.yml
