apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: disktype
              operator: In
              values:
              - not-ssd            
  containers:
  - name: nginx
    image: bitnami/nginx:latest
    imagePullPolicy: IfNotPresent
